{% set name = "csdms-anugased-rectangular" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms-contrib/anuga_BMI

requirements:
  build:
    - bmi-babel
    - anugased-rectangular
    - scipy <=0.18.1
  run:
    - bmi-babel
    - anugased-rectangular
    - scipy <=0.18.1
    - matplotlib

test:
  requires:
    - pymt

about:
  home: https://csdms.colorado.edu/wiki/Model:Anuga
  license: GPLv2
  summary:
    AnugaSedRectangular allows for limited use of ANUGA and anugaSed.
    Use this component for simulations on rectangular domains.
  dev_url: https://github.com/GeoscienceAustralia/anuga_core
